spring:
  application:
    name: springdata
  datasource.url: jdbc:h2:~/springdata;AUTO_SERVER=TRUE
  jpa.hibernate.ddl-auto: create
  jpa.properties.hibernate.show_sql: true
  jpa.properties.hibernate.format_sql: true
  
management:
    security:
        enabled: false
info:
  app:
    name: Spring Data JPA Application
    description: ${info.app.name} is Running on ${server.port} port
      
server:
  port: 8080 